### ISSUE TITLE
numpy.in1d compatibility issue

### ISSUE THREAD

**Issue by andreagebek** [SKIRT/PTS9#53]
**Description**
numpy.in1d has been removed in numpy v2.4.0. This causes the following error when importing pts.band:
AttributeError: module numpy has no attribute in1d. 

**Reproduce**
- Install the latest numpy version from conda (`conda install numpy`)
- `import pts.band`

**Data**
-

**System**
 - Mac M3 OS Tahoe 26.2
 - Python 3.14.2
 - numpy 2.4.1

**Context**
np.in1d should be replaced with np.isin to be consistent with the latest numpy versions.

**Comment by petercamps** [comment]
I'm running numpy 2.4.2 on the same version of Python and macOS as listed by you. I cannot reproduce the problem, and I cannot find any mention of the string "in1d" in the PTS code (most recent public version, i.e. commit d443156).

@andreagebek Could you upgrade to numpy 2.4.2 and pull PTS commit d443156, and let me know whether the problem persists? Thx.

**Comment by andreagebek** [comment]
Hi Peter, thanks for getting back so quickly.
I checked this more thoroughly and I think the problem lies in the astropy import in PTS.

I updated PTS to commit `d443156`, and did the following steps:
`conda create -n testPTS`
`conda install python`
`conda install numpy`
`conda install astropy`

Then, I get an error when running:
`python`
`import pts.band`


Error log:

Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    import pts.band
  File "/Users/agebek/Codes/PTS/pts/band/__init__.py", line 19, in <module>
    from .broadband import BroadBand, builtinBands, builtinBand
  File "/Users/agebek/Codes/PTS/pts/band/broadband.py", line 17, in <module>
    import astropy.units as u
  File "/Users/agebek/anaconda3/envs/testPTS/lib/python3.14/site-packages/astropy/units/__init__.py", line 13, in <module>
    from . import (
    ...<13 lines>...
    )
  File "/Users/agebek/anaconda3/envs/testPTS/lib/python3.14/site-packages/astropy/units/astrophys.py", line 12, in <module>
    from astropy.constants import si as _si
  File "/Users/agebek/anaconda3/envs/testPTS/lib/python3.14/site-packages/astropy/constants/__init__.py", line 27, in <module>
    from . import cgs, si
  File "/Users/agebek/anaconda3/envs/testPTS/lib/python3.14/site-packages/astropy/constants/cgs.py", line 7, in <module>
    from .config import codata, iaudata
  File "/Users/agebek/anaconda3/envs/testPTS/lib/python3.14/site-packages/astropy/constants/config.py", line 15, in <module>
    codata = importlib.import_module(".constants." + phys_version, "astropy")
  File "/Users/agebek/anaconda3/envs/testPTS/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/agebek/anaconda3/envs/testPTS/lib/python3.14/site-packages/astropy/constants/codata2018.py", line 9, in <module>
    from .constant import Constant, EMConstant
  File "/Users/agebek/anaconda3/envs/testPTS/lib/python3.14/site-packages/astropy/constants/constant.py", line 11, in <module>
    from astropy.units.quantity import Quantity
  File "/Users/agebek/anaconda3/envs/testPTS/lib/python3.14/site-packages/astropy/units/quantity.py", line 27, in <module>
    from .quantity_helper import can_have_arbitrary_unit, check_output, converters_and_unit
  File "/Users/agebek/anaconda3/envs/testPTS/lib/python3.14/site-packages/astropy/units/quantity_helper/__init__.py", line 16, in <module>
    from . import erfa, function_helpers, helpers, scipy_special
  File "/Users/agebek/anaconda3/envs/testPTS/lib/python3.14/site-packages/astropy/units/quantity_helper/function_helpers.py", line 1246, in <module>
    @function_helper  # np.in1d deprecated in not NUMPY_LT_2_0.
     ^^^^^^^^^^^^^^^
  File "/Users/agebek/anaconda3/envs/testPTS/lib/python3.14/site-packages/astropy/units/quantity_helper/function_helpers.py", line 205, in __call__
    helps = getattr(module, f.__name__)
  File "/Users/agebek/anaconda3/envs/testPTS/lib/python3.14/site-packages/numpy/__init__.py", line 792, in __getattr__
    raise AttributeError(f"module {__name__!r} has no attribute {attr!r}")
AttributeError: module 'numpy' has no attribute 'in1d'. Did you mean: 'int16'?

I'm attaching a .txt file which lists the installed packages in this conda environment. Most importantly, I have:
- python 3.14.2
- numpy 2.4.1
- astropy 7.1.1

I have also updated numpy to 2.4.2 (from the conda-forge channel through `conda install -c conda-forge numpy=2.4.2`), but the problem persisted.

The same error occurs without invoking PTS at all:
`python`
`import astropy.units`
Is enough to cause the error. So there seems to be an inconsistency between astropy 7.1.1 and the latest numpy packages. 
However, I found that when updating astropy to 7.2.0, no error occurs. So no PTS issue - just requires the very latest astropy when using numpy versions 2.4.0 or higher!

[packages.txt](https://github.com/user-attachments/files/25097233/packages.txt)
