### ISSUE TITLE
AttributeError: module 'pts' has no attribute 'storedtable'

### ISSUE THREAD

**Issue by wolfrayet** [SKIRT/PTS9#1]
**Description**
I follow the instruction in the tutorial [Monochromatic simulation of a dusty disk galaxy with SKIRT](http://www.skirt.ugent.be/version9/_tutorial_basics_mono.html) with SKIRT version 9 and PTS 9. When I try to visualize the output with PTS command, I failed with the warning message `AttributeError: module 'pts' has no attribute 'storedtable'`

**Reproduce**
I follow the instruction in tutorial and type `pts make_images . --prefix=ScatAMR --type=primaryscattered`.
And it fails.

**Data**
Same as in the tutorial [Monochromatic simulation of a dusty disk galaxy with SKIRT](http://www.skirt.ugent.be/version9/_tutorial_basics_mono.html)

**System**
 - Ubuntu 18.04
 - Python 3.6.7

**Context**
The whole warning message is as below

> from .plotstoredtable import plotStoredTableCurve, plotStoredTableInteractive

>  File "/home/julius52700/PTS/pts/visual/plotstoredtable.py", line 19, in <module>

>  import pts.storedtable as stab

>  File "/home/julius52700/PTS/pts/storedtable/__init__.py", line 19, in <module>

> from .conversionspec import createConversionSpecs, ConversionSpecs, ConversionSpec

> File "/home/julius52700/PTS/pts/storedtable/conversionspec.py", line 29, in <module>

> from .convert_band import *

>  File "/home/julius52700/PTS/pts/storedtable/convert_band.py", line 17, in <module>

>  import pts.storedtable as stab

> AttributeError: module 'pts' has no attribute 'storedtable'

**Comment by mbaes** [comment]
Dear wolfrayet,

Thanks for sending this bug report. Peter Camps, the main SKIRT developer, is currently on holiday, so it will take some time before he can reply to your message. I am sure he will have a look at this as soon as he returns.

Kind regards,
Maarten

**Comment by petercamps** [comment]
PTS9 requires python 3.7 but i’m not sure that using 3.6 would cause this issue. Could you try with 3.7?

In any case i will look into it when i’m back. 

Peter

___________________
Peter Camps
peter.camps@telenet.be
peter.camps@me.com
http://users.ugent.be/~pcamps/

**Comment by wolfrayet** [comment]
It seems work well with 3.7. Thanks.
